nginx:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/nginx/vhost.d"    
    - "/etc/nginx/conf.d"
    - "./nginx/html:/usr/share/nginx/html"
    - "./proxy/certs:/etc/nginx/certs:ro"

nginxgen:
  image: jwilder/docker-gen
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./dockergen/templates:/etc/docker-gen/templates"
  volumes_from:
    - nginx
  links:
    - nginx:nginx
  command: "-notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  volumes_from:
    - nginx
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "./proxy/certs:/etc/nginx/certs:rw"
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginxgen

simplesite:
  image: nginx
  volumes:
    - "./nginx/conf.d/:/etc/nginx/conf.d"
  environment:
    - VIRTUAL_HOST=soeleh.com
    - LETSENCRYPT_HOST=soeleh.com
    - LETSENCRYPT_EMAIL=chaluemwut@hotmail.com      